(add-to-list 'load-path "~/git/devil/")
(message "Type <left> x <left> f")
(message "Type <left> g")
(message "Type <left> <left>")
(message "type <left> SPC")
(message "type <left> p p p")
(message "type <left> m m w")
(message "type <left> y")
(message "Type <left> RET (undefined)")
(message "Type <left> x <left> c")

;;; START
(require 'devil)
(global-devil-mode)
(global-set-key (kbd "C-<left>") 'global-devil-mode)
(devil-set-key (kbd "<left>"))
(dolist (key '("%k SPC" "%k RET" "%k <return>"))
  (assoc-delete-all key devil-special-keys))
