(add-to-list 'load-path "~/git/devil/")
(require 'devil)
(global-devil-mode)
(global-set-key (kbd "C-<left>") 'global-devil-mode)
(devil-set-key (kbd "<left>"))
(setq devil-special-keys '(("%k %k" . left-char)))
