(add-to-list 'load-path "~/git/devil/")
(require 'devil)
(setcdr devil-mode-map nil)
(define-key devil-mode-map (kbd ",") #'devil)
(define-key devil-mode-map (kbd "-") #'devil)
(setq devil-special-keys '((", ," . (lambda () (insert ",")))
                           ("- -" . (lambda () (insert "-")))))
(setq devil-translations '(("," . "C-c")
                           ("-" . "C-x")))
(global-devil-mode)
