(add-to-list 'load-path "~/git/devil/")
(require 'devil)
(global-devil-mode)
(define-key devil-mode-map (kbd ".") #'devil)
(setq devil-special-keys '((", ," . (lambda () (insert ",")))
                           (". ." . (lambda () (insert ".")))))
(setq devil-translations '(("," . "C-")
                           ("." . "M-")))
