(add-to-list 'load-path "~/git/devil/")
(message "Type , x , f")
(message "Type , g")
(message "Type , ,")
(message "Type , SPC")
(message "Type , RET")
(message "Type , h , k and , ,")
(message "Type , h , k and , SPC")
(message "Type , h , k and , <return>")
(message "Type , h , k and , x , f")
(message "Type , h , k and , x <tab>")
(message "Type , h , k and , c , c")
(message "Type , h , k and C-x C-f")
(message "Type , h , k and C-c C-c")
(message "Type , h , k and C-c <tab>")
(message "Type , h , k and C-<return>")
(message "Type , x , c")

;;; START
(require 'devil)
(global-devil-mode)
(global-set-key (kbd "C-,") 'global-devil-mode)
